[versions]
undercouch-download = "5.6.0"

[libraries]
# ─────────────────────────────────────────────
# Plugin Development Dependencies
# (used when implementing Gradle plugins)
# ─────────────────────────────────────────────
pluginClasspath-undercouch-download = { module = "de.undercouch.download:de.undercouch.download.gradle.plugin", version.ref = "undercouch-download" }