[versions]
spring-boot = "1.2.1.RELEASE"
spring = "4.1.4.RELEASE"
freemarker = "2.3.21"
h2 = "1.4.183"
liquibase = "3.3.0"
javamail = "1.5.2"
jaxb = "2.3.0"
jsch = "0.1.51"
dcm4che = "2.0.23"
commons-cli = "1.2"
commons-io = "2.4"
junit = "4.12"
hamcrest = "1.3"
selenide = "2.15"
selenium = "2.44.0"
operadriver = "1.5"
lombok = "1.18.42"
mpi = "1.7.4-12022013"
javatuples = "1.2"

[libraries]
apache-log4j = { module = "org.apache.logging.log4j:log4j-core", version.require = "2.25.2" }
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }
jocl = { module = "org.jocl:jocl", version.require = "2.0.5" }
javax-mail = { group = "com.sun.mail", name = "javax.mail", version.ref = "javamail" }

javatuples = { module = "org.javatuples:javatuples", version.ref = "javatuples" }

jaxb-api = { group = "javax.xml.bind", name = "jaxb-api", version.ref = "jaxb" }
jaxb-core = { group = "com.sun.xml.bind", name = "jaxb-core", version.ref = "jaxb" }
jaxb-impl = { group = "com.sun.xml.bind", name = "jaxb-impl", version.ref = "jaxb" }

jsch = { group = "com.jcraft", name = "jsch", version.ref = "jsch" }

spring-core = { group = "org.springframework", name = "spring-core", version.ref = "spring" }
spring-context = { group = "org.springframework", name = "spring-context", version.ref = "spring" }

spring-boot-starter-jdbc = { group = "org.springframework.boot", name = "spring-boot-starter-jdbc", version.ref = "spring-boot" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-freemarker = { group = "org.springframework.boot", name = "spring-boot-starter-freemarker", version.ref = "spring-boot" }
spring-boot-starter-log4j = { group = "org.springframework.boot", name = "spring-boot-starter-log4j", version.ref = "spring-boot" }
spring-boot-starter-tomcat = { group = "org.springframework.boot", name = "spring-boot-starter-tomcat", version.ref = "spring-boot" }

servlet-api = { group = "javax.servlet", name = "javax.servlet-api", version = "3.0.1" }

freemarker = { group = "org.freemarker", name = "freemarker", version.ref = "freemarker" }

liquibase-core = { group = "org.liquibase", name = "liquibase-core", version.ref = "liquibase" }

dcm4che-core = { group = "dcm4che", name = "dcm4che-core", version.ref = "dcm4che" }
dcm4che-imageio = { group = "dcm4che", name = "dcm4che-imageio", version.ref = "dcm4che" }

commons-cli = { group = "commons-cli", name = "commons-cli", version.ref = "commons-cli" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
hamcrest = { group = "org.hamcrest", name = "hamcrest-core", version.ref = "hamcrest" }

selenide = { group = "com.codeborne", name = "selenide", version.ref = "selenide" }
selenium = { group = "org.seleniumhq.selenium", name = "selenium-java", version.ref = "selenium" }
operadriver = { group = "com.opera", name = "operadriver", version.ref = "operadriver" }

lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
